/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        int[] sampleArray = {5, 3, 8, 1, 9};

        System.out.println("For Loop Results:");
        System.out.println("Min: " + ArrayStats.minForLoop(sampleArray));
        System.out.println("Max: " + ArrayStats.maxForLoop(sampleArray));
        System.out.println("Sum: " + ArrayStats.sumForLoop(sampleArray));
        System.out.println("Avg: " + ArrayStats.avgForLoop(sampleArray));

        System.out.println("\nStream API Results:");
        System.out.println("Min: " + ArrayStats.minStream(sampleArray));
        System.out.println("Max: " + ArrayStats.maxStream(sampleArray));
        System.out.println("Sum: " + ArrayStats.sumStream(sampleArray));
        System.out.println("Avg: " + ArrayStats.avgStream(sampleArray));
    }
}

